version: '3'
services:
  app:
    image: ${REGISTER}:latest
    env_file: .env
    ports: 
      - 80:4000
    depends_on:
      - dev-db
  dev-db:
    image: mysql:8.0
    container_name: mystore_db
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my-store-local
      - MYSQL_USER=ductai
      - MYSQL_PASSWORD=superadmin
      - MYSQL_ROOT_PASSWORD=superadmin
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - '6379:6379'