version: '3'
services:
  dev-db:
    image: mysql:8.0
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my-store-local
      - MYSQL_USER=ductai
      - MYSQL_PASSWORD=superadmin
      - MYSQL_ROOT_PASSWORD=superadmin
    ports:
      - 3458:3306
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always